### ISSUE TITLE
Chains disappear on leg cuff poses

### ISSUE THREAD

**Issue by spflanze** [OpenCollarTeam/AddOnCuffs#1]
What version of OpenCollar are you using?
OpenCollar 8.2.1000
OpenCollar Addon Cuffs Version 2.0

What behavior did you expect?
That wrist, and ankle, cuff chains remain visible after the avatar is posed in:
Addons => Leg Chains => Pose => < Legs High | Legs Low >

What behavior did you see instead?
After the "Legs High", and "Legs Low",  poses in that menu are selected leg, and ankle, cuff chains disappear.

What steps does someone need to take to reproduce the problem?
1) Attach the collar, and only the wrist, and ankle cuffs. The thigh, and arm, cuffs, and the belt, were not attached. They are not needed for the RP I intend to do.
2) Navigate to: Addons => Leg Chains => Pose => Chain Only
3) Navigate to: Addons => Arm Chains => Pose => Front 2
4) Navigate to Navigate to: Addons => Leg Chains => Pose => Legs High, and the chains disappear. they also disappear if "Legs Low" is selected.

**Comment by Pingout** [comment]
Wow, this Issue was from a long time ago!
So the fix for this is not a script revision. The fix would be in the Legs notecard, which issues the commands based on the pose selected. 
If you want Ankle Chains added to the "Legs Low" pose, change the notecard to this:

"PoseName:Legs Low"
"PoseAnim:LLL P6"
"PoseChains:lulc=lllc~rulc=rllc~irllc=illlc"

I added the Tilde (~) Inside Right Lower Leg Cuff (irllc) Equals (=) Inside Left Lower Leg Cuff (illlc)
where the = sign is the chain, and the ~ sign is the separator
